### ISSUE TITLE
InnoSetup 6.3.1 Seek bug

### ISSUE THREAD

**Issue by ColossalFossil** [amake/innosetup-docker#18]
I encountered runtime errors using an installer built with InnoSetup 6.3.1, when the installer tried to Seek through Pascal.  Locally I was able to substitute 6.3.2 in the docker file and produce working installers again.

Internal error: Expression error 'Runtime error (at <position x>): Access violation at address 00000000 in module 'application-setup.tmp'.  Execution of address 00000000.'

_Changelog for innosetup noting seek repair:_
https://jrsoftware.org/files/is6-whatsnew.htm

_Discussion of issue and fix_
https://groups.google.com/g/innosetup/c/F0Umj7hKO_U/m/79lJBeLKAAAJ

Windows 11 x64, under VMWare Fusion7,1

**Comment by amake** [comment]
Thanks. 6.3.3 was released in the meantime so I upgraded to that.

**Comment by ColossalFossil** [comment]
Thank you very much, I confirmed that the issue is gone during installer testing.
